### ISSUE TITLE
Broken latest build and stale stable build

### ISSUE THREAD

**Issue by RallySmith** [renode/renode-issue-reproduction-template#4]
Background: I have a lot of STM32 (F207 and H723) model fixes/feature-extensions that I implemented for a customer against their existing hardware designs and some in-development products to allow the shipped release binaries to be executed under Renode. The model updates having been extensively tested over 1000s of test runs in an automated test farm (not robot based).

So creating a fork of renode-issue-reproduction-template seemed the obvious starting point for providing the generic STM32 updates with the goal of them making it to the renode main repo. The initial target being supporting how the eCos DMA driven, timer triggered, ADC driver makes use of the RM0033 (STM32F2xx) hardware.

Unfortunately it seems that there are two issues hindering the initial progress of providing an issue fork to 1) demonstrate bugs/missing-functionality in the latest renode, and 2) provide changesets to fix/extend as a starting point for hopefully having the updated models included in the mainline.

FYI see:
  https://github.com/RallySmith/renode-issue-stm32f2-adc-dma/actions/runs/8813661348/job/24191867392

**A**) the `latest` tarball is not extracted/accessed cleanly resulting in the "Run tests on latest Renode" just failing with "Renode not yet installed".  I did try tweaking the test.yaml, and also looking at the renode-run and renode-test-action repos but nothing immediately popped out as to why the github workflow case fails; especially when doing the exact same operations manually on a Kubuntu 22.04 system works with regards to extracting the latest tarball into a named directory.

**B**) the `stable` is "stale" with regards to features present on the renode mainline. The workflow is using 1.13.3, which manifests in this specific fork case with the renode execution not finding the STM32F4_EXTI as referenced from the CPU. I could tweak the  renode-issue-stm32f2-adc-dma fork to provide a stm32f2.repl that does NOT reference that model; but it feels like the template should be referencing 1.15.0 as the most recent stable release.

Aside: Apologies for the typo in the https://github.com/RallySmith/renode-issue-stm32f2-adc-dma/blob/main/README.md saying 1.15.9, when it should be 1.15.0 :-) Not yet worthy of pushing a commit just for that; especially since a renode run is not actually starting yet for the fork.

**Comment by PiotrZierhoffer** [comment]
Hi @RallySmith ,

Thanks for pointing this out. You can see we have updated this repository - can you please rebase your branch on top of our recent changes?

These changes include update to the "stable" and also using our latest version of the [renode-test-action](https://github.com/antmicro/renode-test-action).

Please let us know if it helps!

**Comment by RallySmith** [comment]
Thanks!

That has at least unstuck the renode runs. There are still "errors" in the build world reported in the log; but at least renode is now executing the base .resc/.repl/etc. setup; and the first issue I intend to commit a changeset for is highlighted in the action report :-)

https://github.com/RallySmith/renode-issue-stm32f2-adc-dma/actions/runs/8877639934/job/24371627244

I will create a local branch in my fork and start to push the changesets, and hopefully the work can eventually make it to the mainline. For the moment I will mark this issue as closed.

Cheers!
